apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: todoapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-list
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-binding
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: secret-reader
  namespace: todoapp
roleRef:
  kind: Role
  name: secret-list
  apiGroup: rbac.authorization.k8s.io
